### ISSUE TITLE
Getting from Point A to Point B

### ISSUE THREAD

**Issue by antithalian** [antithalian/pydown#1]
How to get from Point A (nothing!) to Point B (bare minimum functionality for prod):

- [x] be able to read in Markdown and output a valid HTML page

- [ ] be able to build a more complex page with a *real* header and footer

- [ ] be able to read in and build multiple Markdown files and output multiple HTML files

- [ ] support multiple different types of page (not just straight header - (MD -> HTML) - footer)

    - [ ] some form of loading configuration/specifying HTML stubs?

    - [ ] ability to use separate HTML stubs

Will add more later as I think of it...

**Comment by antithalian** [comment]
Thinking the best way to support configuration/specification for final goal is a class in another file that just holds the configuration...

No point pulling in JSON or something just to hand edit it. Just adds an extra step for me or whoever comes after me.
